// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MUMS.Web.Controllers {
    public partial class RootController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RootController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RootController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddRemoteUrl() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddRemoteUrl);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AddTorrent() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddTorrent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult UploadFiles() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.UploadFiles);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult StartTorrent() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.StartTorrent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult StopTorrent() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.StopTorrent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult RemoveTorrent() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.RemoveTorrent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult RemoveTorrentAndData() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.RemoveTorrentAndData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult TorrentAction() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.TorrentAction);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SetLabel() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SetLabel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetTorrent() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetTorrent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult JsonContract() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.JsonContract);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RootController Actions { get { return MVC.Root; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Root";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string GetEpisodes = "GetEpisodes";
            public readonly string GetTorrents = "GetTorrents";
            public readonly string AddRemoteUrl = "AddRemoteUrl";
            public readonly string AddTorrent = "AddTorrent";
            public readonly string UploadFiles = "UploadFiles";
            public readonly string StartTorrent = "StartTorrent";
            public readonly string StopTorrent = "StopTorrent";
            public readonly string RemoveTorrent = "RemoveTorrent";
            public readonly string RemoveTorrentAndData = "RemoveTorrentAndData";
            public readonly string TorrentAction = "TorrentAction";
            public readonly string SetLabel = "SetLabel";
            public readonly string GetTorrent = "GetTorrent";
            public readonly string ClearFinished = "ClearFinished";
            public readonly string JsonContract = "JsonContract";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Index = "~/Views/Root/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_RootController: MUMS.Web.Controllers.RootController {
        public T4MVC_RootController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetEpisodes() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetEpisodes);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetTorrents() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetTorrents);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddRemoteUrl(string url, string label) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddRemoteUrl);
            callInfo.RouteValueDictionary.Add("url", url);
            callInfo.RouteValueDictionary.Add("label", label);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddTorrent(string url, string label) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddTorrent);
            callInfo.RouteValueDictionary.Add("url", url);
            callInfo.RouteValueDictionary.Add("label", label);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UploadFiles(string label) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UploadFiles);
            callInfo.RouteValueDictionary.Add("label", label);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult StartTorrent(string hash) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.StartTorrent);
            callInfo.RouteValueDictionary.Add("hash", hash);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult StopTorrent(string hash) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.StopTorrent);
            callInfo.RouteValueDictionary.Add("hash", hash);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RemoveTorrent(string hash) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RemoveTorrent);
            callInfo.RouteValueDictionary.Add("hash", hash);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult RemoveTorrentAndData(string hash) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.RemoveTorrentAndData);
            callInfo.RouteValueDictionary.Add("hash", hash);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TorrentAction(string hash, System.Func<MUMS.Utorrent.Service.DefaultResponse> action) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TorrentAction);
            callInfo.RouteValueDictionary.Add("hash", hash);
            callInfo.RouteValueDictionary.Add("action", action);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult SetLabel(string newLabel, string hash) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SetLabel);
            callInfo.RouteValueDictionary.Add("newLabel", newLabel);
            callInfo.RouteValueDictionary.Add("hash", hash);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetTorrent(string hash) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetTorrent);
            callInfo.RouteValueDictionary.Add("hash", hash);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ClearFinished() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ClearFinished);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult JsonContract(object obj) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.JsonContract);
            callInfo.RouteValueDictionary.Add("obj", obj);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
