#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUMS.Web.Models.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mums")]
	public partial class MumsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertRssEpisodeItem(RssEpisodeItem instance);
    partial void UpdateRssEpisodeItem(RssEpisodeItem instance);
    partial void DeleteRssEpisodeItem(RssEpisodeItem instance);
    #endregion
		
		public MumsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["mumsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MumsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MumsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MumsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MumsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<RssEpisodeItem> RssEpisodeItems
		{
			get
			{
				return this.GetTable<RssEpisodeItem>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Token;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTokenChanging(string value);
    partial void OnTokenChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Token", DbType="NChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Token
		{
			get
			{
				return this._Token;
			}
			set
			{
				if ((this._Token != value))
				{
					this.OnTokenChanging(value);
					this.SendPropertyChanging();
					this._Token = value;
					this.SendPropertyChanged("Token");
					this.OnTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RssEpisodeItems")]
	public partial class RssEpisodeItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RssEpisodeItemId;
		
		private string _ReleaseName;
		
		private int _Season;
		
		private int _Episode;
		
		private bool _Download;
		
		private System.DateTime _PubDate;
		
		private System.Nullable<int> _DuplicateOf;
		
		private System.DateTime _Added;
		
		private long _EnclosureLength;
		
		private string _EnclosureUrl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRssEpisodeItemIdChanging(int value);
    partial void OnRssEpisodeItemIdChanged();
    partial void OnReleaseNameChanging(string value);
    partial void OnReleaseNameChanged();
    partial void OnSeasonChanging(int value);
    partial void OnSeasonChanged();
    partial void OnEpisodeChanging(int value);
    partial void OnEpisodeChanged();
    partial void OnDownloadChanging(bool value);
    partial void OnDownloadChanged();
    partial void OnPubDateChanging(System.DateTime value);
    partial void OnPubDateChanged();
    partial void OnDuplicateOfChanging(System.Nullable<int> value);
    partial void OnDuplicateOfChanged();
    partial void OnAddedChanging(System.DateTime value);
    partial void OnAddedChanged();
    partial void OnEnclosureLengthChanging(long value);
    partial void OnEnclosureLengthChanged();
    partial void OnEnclosureUrlChanging(string value);
    partial void OnEnclosureUrlChanged();
    #endregion
		
		public RssEpisodeItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RssEpisodeItemId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RssEpisodeItemId
		{
			get
			{
				return this._RssEpisodeItemId;
			}
			set
			{
				if ((this._RssEpisodeItemId != value))
				{
					this.OnRssEpisodeItemIdChanging(value);
					this.SendPropertyChanging();
					this._RssEpisodeItemId = value;
					this.SendPropertyChanged("RssEpisodeItemId");
					this.OnRssEpisodeItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseName", DbType="NChar(255) NOT NULL", CanBeNull=false)]
		public string ReleaseName
		{
			get
			{
				return this._ReleaseName;
			}
			set
			{
				if ((this._ReleaseName != value))
				{
					this.OnReleaseNameChanging(value);
					this.SendPropertyChanging();
					this._ReleaseName = value;
					this.SendPropertyChanged("ReleaseName");
					this.OnReleaseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Season", DbType="Int NOT NULL")]
		public int Season
		{
			get
			{
				return this._Season;
			}
			set
			{
				if ((this._Season != value))
				{
					this.OnSeasonChanging(value);
					this.SendPropertyChanging();
					this._Season = value;
					this.SendPropertyChanged("Season");
					this.OnSeasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Episode", DbType="Int NOT NULL")]
		public int Episode
		{
			get
			{
				return this._Episode;
			}
			set
			{
				if ((this._Episode != value))
				{
					this.OnEpisodeChanging(value);
					this.SendPropertyChanging();
					this._Episode = value;
					this.SendPropertyChanged("Episode");
					this.OnEpisodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Download", DbType="Bit NOT NULL")]
		public bool Download
		{
			get
			{
				return this._Download;
			}
			set
			{
				if ((this._Download != value))
				{
					this.OnDownloadChanging(value);
					this.SendPropertyChanging();
					this._Download = value;
					this.SendPropertyChanged("Download");
					this.OnDownloadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PubDate", DbType="DateTime NOT NULL")]
		public System.DateTime PubDate
		{
			get
			{
				return this._PubDate;
			}
			set
			{
				if ((this._PubDate != value))
				{
					this.OnPubDateChanging(value);
					this.SendPropertyChanging();
					this._PubDate = value;
					this.SendPropertyChanged("PubDate");
					this.OnPubDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuplicateOf", DbType="Int")]
		public System.Nullable<int> DuplicateOf
		{
			get
			{
				return this._DuplicateOf;
			}
			set
			{
				if ((this._DuplicateOf != value))
				{
					this.OnDuplicateOfChanging(value);
					this.SendPropertyChanging();
					this._DuplicateOf = value;
					this.SendPropertyChanged("DuplicateOf");
					this.OnDuplicateOfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Added", DbType="DateTime NOT NULL")]
		public System.DateTime Added
		{
			get
			{
				return this._Added;
			}
			set
			{
				if ((this._Added != value))
				{
					this.OnAddedChanging(value);
					this.SendPropertyChanging();
					this._Added = value;
					this.SendPropertyChanged("Added");
					this.OnAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnclosureLength", DbType="BigInt NOT NULL")]
		public long EnclosureLength
		{
			get
			{
				return this._EnclosureLength;
			}
			set
			{
				if ((this._EnclosureLength != value))
				{
					this.OnEnclosureLengthChanging(value);
					this.SendPropertyChanging();
					this._EnclosureLength = value;
					this.SendPropertyChanged("EnclosureLength");
					this.OnEnclosureLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnclosureUrl", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string EnclosureUrl
		{
			get
			{
				return this._EnclosureUrl;
			}
			set
			{
				if ((this._EnclosureUrl != value))
				{
					this.OnEnclosureUrlChanging(value);
					this.SendPropertyChanging();
					this._EnclosureUrl = value;
					this.SendPropertyChanged("EnclosureUrl");
					this.OnEnclosureUrlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
